# Generated by Django 5.0.2 on 2024-02-18 18:38

import src.apps.events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Title')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('date', models.DateTimeField(validators=[src.apps.events.validators.validate_event_date], verbose_name='Date')),
                ('location', models.CharField(max_length=128, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
